os:
  - linux

before_install:
  - |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    openssl aes-256-cbc -K $encrypted_86dc7fa5806f_key -iv $encrypted_86dc7fa5806f_iv -in .ci/deploy_key.enc -out "$SSH_FILE" -d
    chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  LogLevel ERROR" >> ~/.ssh/config
  - git config --global user.email "howi@okramlabs.com"
  - git config --global user.name "howi-bot"

script:
  - git filter-branch --prune-empty --subdirectory-filter public master
  - git remote add ghpage git@github.com:okramlabs/okramlabs.github.io.git
  - git push -f ghpage master

branches:
  only:
  - master

notifications:
  email: false
