os:
  - linux

branches:
  only:
  - master

notifications:
  email: false

before_install: ./howi-bot --as-howi-bot travis-ci before_install

install: ./howi-bot --as-howi-bot travis-ci install

before_script: ./howi-bot --as-howi-bot travis-ci before_script

script: ./howi-bot --as-howi-bot travis-ci before_script

after_success: ./howi-bot --as-howi-bot travis-ci after_success

after_failure: ./howi-bot --as-howi-bot travis-ci after_failure

before_deploy: ./howi-bot --as-howi-bot travis-ci before_deploy

deploy:
  provider: script
  script: ./howi-bot --as-howi-bot travis-ci deploy
  on:
    tags: true
    branch: master

after_deploy: ./howi-bot --as-howi-bot travis-ci after_deploy

after_script: ./howi-bot --as-howi-bot travis-ci after_script
